create table if not exists public.score_snapshots (
  id bigint generated by default as identity primary key,
  event_id text not null,
  event_status text,
  round_number smallint check (round_number between 1 and 4),
  captured_minute timestamptz not null,
  payload jsonb not null,
  captured_at timestamptz not null default now(),
  unique (event_id, captured_minute)
);

create index if not exists score_snapshots_event_captured_idx
  on public.score_snapshots (event_id, captured_at desc);

alter table public.score_snapshots enable row level security;

drop policy if exists "Public can read score snapshots" on public.score_snapshots;
create policy "Public can read score snapshots"
  on public.score_snapshots for select
  to anon, authenticated
  using (true);

create or replace view public.latest_score_snapshot as
select distinct on (event_id) *
from public.score_snapshots
order by event_id, captured_at desc;
